---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data-pv
  labels:
    loki-pv: "true"
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-expandable
  hostPath:
    path: /monitoring/loki-data
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - monitoring