// Region-scoped mock analytics for the dashboard (master + per-region drill-down).
// Single source of truth: every Box 1–7 value on /dashboard/region/[code] and the
// master page's map/table read from here. Country/region datasets are generated by
// deterministically scaling the global baseline (share factors consistent with the
// activity map's country data and the slide-6 table: APAC 56% / NA 29% / EU 24% /
// LATAM 10% / MEA 5%) with small per-metric jitter so pages don't look copy-pasted.
// Numbers stay internally consistent: users sum ≈ 248.5K signed up, the viewers /
// gamified splits match the master table, and the map, master row, and region strips agree.

import { MACRO_REGIONS, type MacroRegion, regionForCountry } from "@/app/_libs/regions";

/* ------------------------------- map countries ------------------------------- */

export interface CountryData {
  code: string;
  name: string;
  users: number;
  revenue: number;
  points: number; // points earned (gamification activity)
  intensity: number; // 0-1
}

// Users sum to ~248,500 and revenue to ~$98.5K MRR (consistent with the dashboard + regional views).
export const COUNTRY_DATA: CountryData[] = [
  { code: "US", name: "United States", users: 58000, revenue: 33000, points: 4200000, intensity: 0.9 },
  { code: "IN", name: "India", users: 47000, revenue: 11500, points: 6100000, intensity: 0.75 },
  { code: "GB", name: "United Kingdom", users: 26000, revenue: 18000, points: 720000, intensity: 0.55 },
  { code: "AU", name: "Australia", users: 23000, revenue: 6000, points: 640000, intensity: 0.45 },
  { code: "DE", name: "Germany", users: 22000, revenue: 13000, points: 510000, intensity: 0.4 },
  { code: "JP", name: "Japan", users: 21000, revenue: 8000, points: 2800000, intensity: 0.5 },
  { code: "KR", name: "South Korea", users: 12000, revenue: 3000, points: 2300000, intensity: 0.35 },
  { code: "ID", name: "Indonesia", users: 12000, revenue: 1800, points: 2600000, intensity: 0.3 },
  { code: "PH", name: "Philippines", users: 9000, revenue: 1500, points: 3100000, intensity: 0.28 },
  { code: "TH", name: "Thailand", users: 7500, revenue: 1000, points: 1700000, intensity: 0.22 },
  { code: "VN", name: "Vietnam", users: 6000, revenue: 800, points: 1500000, intensity: 0.18 },
  { code: "MY", name: "Malaysia", users: 5000, revenue: 900, points: 1100000, intensity: 0.15 },
];

/* --------------------------------- shapes --------------------------------- */

export interface UserAnalyticsData {
  starts: number;
  completes: number;
  avgWatchPct: number; // % of video watched
  avgWatchSecs: number;
  avgClipSecs: number;
  swipeThroughPct: number; // abandonment — lower is better
  rewatchLoops: number;
  engagementPerSession: number; // likes+shares+saves+comments
  videosPerSession: number;
  videosPerDay: number;
  completionLivePct: number; // completion rate, live library
  hitRatePct: number; // new uploads >10K views in 30d
}

export interface GamificationData {
  earnedPerUserDay: number;
  redemptionPct: number; // % of issued points redeemed
  pointsOutstanding: number;
  streakAvgDays: number;
  streakLongestDays: number;
  leaderboardChecksPerWeek: number; // how often users check the leaderboard
  rankChangeAvgWeek: number; // avg absolute rank movement / week
  challengeParticipationPct: number;
  challengeCompletionPct: number;
  /** % split — which actions drive engagement vs inflate balances */
  earnedBySource: { name: string; value: number; color: string }[];
  /** who is holding points */
  balanceBuckets: { bucket: string; pct: number }[];
  economyTrend: { period: string; distributed: number; redeemed: number }[];
  redemptionTrend: { week: string; rate: number }[];
}

export interface ScreenTimeData {
  viewers: number; // viewership (not active)
  gamified: number; // viewership WITH active gamification
  sessionAvgSecs: number;
  sessionMedianSecs: number;
  /** session length distribution — % per bucket */
  sessionBuckets: { bucket: string; pct: number }[];
  /** 7 rows (Mon..Sun) × 24 cols — relative intensity 0-1 */
  heatmap: number[][];
  bgFgPerSession: number; // background↔foreground transitions (re-entries)
  doomscrollVideos: number; // videos per session
  doomscrollMinutes: number; // minutes per user
}

export interface MonetizationData {
  arpu: number;
  arpdau: number;
  trialToPaidPct: number;
  ltvCacRatio: number;
  funnel: { signups: number; firstSession: number; engaged: number; subscribed: number; referred: number };
  channels: { channel: string; ltv: number; cac: number }[];
  subsTrend: { date: string; newSubs: number; cancellations: number }[];
  revenueTrend: { month: string; subscriptions: number }[];
}

export interface CommunityData {
  inApp: {
    commentsPerUserWeek: number;
    replyRatePct: number;
    reactionToViewPct: number;
    sharesPerVideo: number;
  };
  external: {
    mentionsPerWeek: number;
    sentiment: [number, number, number]; // % pos / neutral / neg
    viralMoments: number;
    organicImpressions: number;
    earnedMediaValue: number;
    topAdvocates: number;
  };
}

export interface GraphsData {
  retention: { d1: number; d7: number; d30: number; series: { day: string; current: number; previous: number }[] };
  kFactor: { month: string; k: number }[];
  velocity: { day: string; players: number }[];
}

export interface RegionAnalytics {
  code: string;
  name: string;
  /** parent macro-region for country pages */
  macro?: MacroRegion;
  /** share of the global baseline this scope represents */
  factor: number;
  strip: { users: number; subscribers: number; onlineNow: number; playingNow: number };
  userAnalytics: UserAnalyticsData;
  gamification: GamificationData;
  screenTime: ScreenTimeData;
  monetization: MonetizationData;
  community: CommunityData;
  graphs: GraphsData;
}

/* ------------------------------ global baseline ------------------------------ */

// 7×24 time-of-day intensity: evenings peak, weekends heavier — deterministic, no RNG.
const buildHeatmap = (boost = 1): number[][] =>
  Array.from({ length: 7 }, (_, d) => {
    const weekend = d >= 5 ? 1.15 : 1;
    return Array.from({ length: 24 }, (_, h) => {
      // low overnight, lunch bump, strong 18–22 peak
      const base =
        h < 6 ? 0.08 + h * 0.01 : h < 11 ? 0.25 + (h - 6) * 0.04 : h < 14 ? 0.5 : h < 18 ? 0.42 : h < 23 ? 0.7 + (21 - Math.abs(h - 21)) * 0.15 : 0.3;
      return Math.min(1, Number((base * weekend * boost).toFixed(2)));
    });
  });

const GLOBAL_BASE: Omit<RegionAnalytics, "code" | "name" | "factor" | "macro"> = {
  strip: { users: 248500, subscribers: 8923, onlineNow: 12405, playingNow: 3847 },
  userAnalytics: {
    starts: 1840000,
    completes: 1250000,
    avgWatchPct: 82,
    avgWatchSecs: 18.6,
    avgClipSecs: 22.7,
    swipeThroughPct: 11.3,
    rewatchLoops: 2.1,
    engagementPerSession: 4.7,
    videosPerSession: 14.2,
    videosPerDay: 38,
    completionLivePct: 64,
    hitRatePct: 62,
  },
  gamification: {
    earnedPerUserDay: 312,
    redemptionPct: 49,
    pointsOutstanding: 8400000,
    streakAvgDays: 6.4,
    streakLongestDays: 41,
    leaderboardChecksPerWeek: 3.1,
    rankChangeAvgWeek: 142,
    challengeParticipationPct: 27,
    challengeCompletionPct: 62,
    earnedBySource: [
      { name: "Watching", value: 42, color: "hsl(217, 91%, 60%)" },
      { name: "Streaks", value: 23, color: "hsl(38, 92%, 50%)" },
      { name: "Sharing", value: 16, color: "hsl(270, 91%, 65%)" },
      { name: "Referrals", value: 12, color: "hsl(142, 71%, 45%)" },
      { name: "Challenges", value: 7, color: "hsl(0, 84%, 60%)" },
    ],
    balanceBuckets: [
      { bucket: "0–500", pct: 38 },
      { bucket: "500–2K", pct: 31 },
      { bucket: "2K–10K", pct: 22 },
      { bucket: "10K+", pct: 9 },
    ],
    economyTrend: [
      { period: "Week 1", distributed: 125000, redeemed: 42000 },
      { period: "Week 2", distributed: 148000, redeemed: 55000 },
      { period: "Week 3", distributed: 132000, redeemed: 48000 },
      { period: "Week 4", distributed: 165000, redeemed: 62000 },
    ],
    redemptionTrend: [
      { week: "W1", rate: 34 },
      { week: "W2", rate: 37 },
      { week: "W3", rate: 36 },
      { week: "W4", rate: 41 },
      { week: "W5", rate: 44 },
      { week: "W6", rate: 47 },
      { week: "W7", rate: 49 },
    ],
  },
  screenTime: {
    viewers: 62800, // sum of the master table's regional viewers
    gamified: 38800,
    sessionAvgSecs: 1478, // 24:38
    sessionMedianSecs: 1090, // 18:10
    sessionBuckets: [
      { bucket: "<5m", pct: 18 },
      { bucket: "5–15m", pct: 27 },
      { bucket: "15–30m", pct: 29 },
      { bucket: "30–60m", pct: 19 },
      { bucket: ">60m", pct: 7 },
    ],
    heatmap: buildHeatmap(),
    bgFgPerSession: 3.1,
    doomscrollVideos: 23,
    doomscrollMinutes: 26,
  },
  monetization: {
    arpu: 11.04,
    arpdau: 0.34,
    trialToPaidPct: 31,
    ltvCacRatio: 4.6,
    funnel: { signups: 248500, firstSession: 198000, engaged: 120000, subscribed: 8923, referred: 62125 },
    channels: [
      { channel: "Organic / viral", ltv: 84, cac: 6 },
      { channel: "Referral", ltv: 78, cac: 9 },
      { channel: "Paid social", ltv: 61, cac: 22 },
      { channel: "Influencer", ltv: 69, cac: 18 },
    ],
    subsTrend: [
      { date: "Jan 1", newSubs: 1200, cancellations: 180 },
      { date: "Jan 8", newSubs: 1450, cancellations: 210 },
      { date: "Jan 15", newSubs: 1380, cancellations: 165 },
      { date: "Jan 22", newSubs: 1620, cancellations: 195 },
      { date: "Jan 29", newSubs: 1780, cancellations: 220 },
      { date: "Feb 5", newSubs: 1550, cancellations: 175 },
      { date: "Feb 12", newSubs: 1890, cancellations: 240 },
      { date: "Feb 19", newSubs: 2100, cancellations: 198 },
      { date: "Feb 26", newSubs: 1950, cancellations: 215 },
      { date: "Mar 5", newSubs: 2250, cancellations: 185 },
    ],
    revenueTrend: [
      { month: "Jul", subscriptions: 42000 },
      { month: "Aug", subscriptions: 48000 },
      { month: "Sep", subscriptions: 52000 },
      { month: "Oct", subscriptions: 58000 },
      { month: "Nov", subscriptions: 65000 },
      { month: "Dec", subscriptions: 72000 },
      { month: "Jan", subscriptions: 78000 },
    ],
  },
  community: {
    inApp: { commentsPerUserWeek: 1.8, replyRatePct: 42, reactionToViewPct: 7.8, sharesPerVideo: 184 },
    external: {
      mentionsPerWeek: 2340,
      sentiment: [68, 22, 10],
      viralMoments: 3,
      organicImpressions: 14200000,
      earnedMediaValue: 182000,
      topAdvocates: 12,
    },
  },
  graphs: {
    retention: {
      d1: 58,
      d7: 38,
      d30: 24,
      series: [
        { day: "D0", current: 100, previous: 100 },
        { day: "D1", current: 58, previous: 52 },
        { day: "D3", current: 46, previous: 41 },
        { day: "D7", current: 38, previous: 33 },
        { day: "D14", current: 30, previous: 26 },
        { day: "D30", current: 24, previous: 19 },
      ],
    },
    kFactor: [
      { month: "Jan", k: 0.62 },
      { month: "Feb", k: 0.71 },
      { month: "Mar", k: 0.78 },
      { month: "Apr", k: 0.85 },
      { month: "May", k: 0.94 },
      { month: "Jun", k: 1.06 },
    ],
    velocity: [
      { day: "Mon", players: 42500 },
      { day: "Tue", players: 38200 },
      { day: "Wed", players: 45800 },
      { day: "Thu", players: 41200 },
      { day: "Fri", players: 52400 },
      { day: "Sat", players: 68500 },
      { day: "Sun", players: 72100 },
    ],
  },
};

/* ------------------------------ scaling helpers ------------------------------ */

/** Deterministic 0-1 hash from a string + salt (no RNG — stable across renders/SSR). */
const seeded = (key: string, salt: number): number => {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < key.length; i++) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return ((h >>> 0) % 1000) / 1000;
};

/** Multiplicative jitter in [1-spread, 1+spread] so regions don't look copy-pasted. */
const jitter = (key: string, salt: number, spread = 0.08) => 1 + (seeded(key, salt) * 2 - 1) * spread;

const round = (n: number, dp = 0) => {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
};

/** Scale the global baseline to a region: counts scale by factor, rates/ratios only jitter. */
export function scaleAnalytics(
  code: string,
  name: string,
  factor: number,
  macro?: MacroRegion,
): RegionAnalytics {
  const j = (salt: number, spread?: number) => jitter(code, salt, spread);
  const cnt = (v: number, salt: number) => Math.round(v * factor * j(salt));
  const pct = (v: number, salt: number) => round(Math.min(97, v * j(salt, 0.06)), 1);
  const num = (v: number, salt: number, dp = 1) => round(v * j(salt, 0.07), dp);

  const b = GLOBAL_BASE;
  const gamified = cnt(b.screenTime.gamified, 31);
  const viewers = Math.max(gamified + 1, cnt(b.screenTime.viewers, 30));
  const signups = cnt(b.monetization.funnel.signups, 40);
  const firstSession = Math.round(signups * 0.8 * j(41, 0.04));
  const engaged = Math.round(firstSession * 0.6 * j(42, 0.05));
  const subscribed = cnt(b.monetization.funnel.subscribed, 43);

  return {
    code,
    name,
    macro,
    factor,
    strip: {
      users: cnt(b.strip.users, 1),
      subscribers: cnt(b.strip.subscribers, 2),
      onlineNow: cnt(b.strip.onlineNow, 3),
      playingNow: cnt(b.strip.playingNow, 4),
    },
    userAnalytics: {
      starts: cnt(b.userAnalytics.starts, 10),
      completes: cnt(b.userAnalytics.completes, 11),
      avgWatchPct: pct(b.userAnalytics.avgWatchPct, 12),
      avgWatchSecs: num(b.userAnalytics.avgWatchSecs, 13),
      avgClipSecs: num(b.userAnalytics.avgClipSecs, 14),
      swipeThroughPct: pct(b.userAnalytics.swipeThroughPct, 15),
      rewatchLoops: num(b.userAnalytics.rewatchLoops, 16),
      engagementPerSession: num(b.userAnalytics.engagementPerSession, 17),
      videosPerSession: num(b.userAnalytics.videosPerSession, 18),
      videosPerDay: num(b.userAnalytics.videosPerDay, 19, 0),
      completionLivePct: pct(b.userAnalytics.completionLivePct, 20),
      hitRatePct: pct(b.userAnalytics.hitRatePct, 21),
    },
    gamification: {
      earnedPerUserDay: num(b.gamification.earnedPerUserDay, 50, 0),
      redemptionPct: pct(b.gamification.redemptionPct, 51),
      pointsOutstanding: cnt(b.gamification.pointsOutstanding, 52),
      streakAvgDays: num(b.gamification.streakAvgDays, 53),
      streakLongestDays: num(b.gamification.streakLongestDays, 54, 0),
      leaderboardChecksPerWeek: num(b.gamification.leaderboardChecksPerWeek, 55),
      rankChangeAvgWeek: num(b.gamification.rankChangeAvgWeek, 56, 0),
      challengeParticipationPct: pct(b.gamification.challengeParticipationPct, 57),
      challengeCompletionPct: pct(b.gamification.challengeCompletionPct, 58),
      earnedBySource: b.gamification.earnedBySource,
      balanceBuckets: b.gamification.balanceBuckets,
      economyTrend: b.gamification.economyTrend.map((r, i) => ({
        period: r.period,
        distributed: cnt(r.distributed, 60 + i),
        redeemed: cnt(r.redeemed, 70 + i),
      })),
      redemptionTrend: b.gamification.redemptionTrend.map((r, i) => ({
        week: r.week,
        rate: pct(r.rate, 80 + i),
      })),
    },
    screenTime: {
      viewers,
      gamified,
      sessionAvgSecs: Math.round(b.screenTime.sessionAvgSecs * j(90, 0.1)),
      sessionMedianSecs: Math.round(b.screenTime.sessionMedianSecs * j(91, 0.1)),
      sessionBuckets: b.screenTime.sessionBuckets,
      heatmap: buildHeatmap(0.85 + seeded(code, 92) * 0.3),
      bgFgPerSession: num(b.screenTime.bgFgPerSession, 93),
      doomscrollVideos: num(b.screenTime.doomscrollVideos, 94, 0),
      doomscrollMinutes: num(b.screenTime.doomscrollMinutes, 95, 0),
    },
    monetization: {
      arpu: num(b.monetization.arpu, 100, 2),
      arpdau: num(b.monetization.arpdau, 101, 2),
      trialToPaidPct: pct(b.monetization.trialToPaidPct, 102),
      ltvCacRatio: num(b.monetization.ltvCacRatio, 103),
      funnel: {
        signups,
        firstSession,
        engaged,
        subscribed: Math.min(subscribed, engaged),
        referred: Math.round(signups * 0.25 * j(44, 0.1)),
      },
      channels: b.monetization.channels.map((c, i) => ({
        channel: c.channel,
        ltv: num(c.ltv, 110 + i, 0),
        cac: num(c.cac, 120 + i, 0),
      })),
      subsTrend: b.monetization.subsTrend.map((r, i) => ({
        date: r.date,
        newSubs: cnt(r.newSubs, 130 + i),
        cancellations: cnt(r.cancellations, 150 + i),
      })),
      revenueTrend: b.monetization.revenueTrend.map((r, i) => ({
        month: r.month,
        subscriptions: cnt(r.subscriptions, 170 + i),
      })),
    },
    community: {
      inApp: {
        commentsPerUserWeek: num(b.community.inApp.commentsPerUserWeek, 200),
        replyRatePct: pct(b.community.inApp.replyRatePct, 201),
        reactionToViewPct: num(b.community.inApp.reactionToViewPct, 202),
        sharesPerVideo: num(b.community.inApp.sharesPerVideo, 203, 0),
      },
      external: {
        mentionsPerWeek: cnt(b.community.external.mentionsPerWeek, 210),
        sentiment: b.community.external.sentiment,
        viralMoments: Math.max(1, cnt(b.community.external.viralMoments, 211)),
        organicImpressions: cnt(b.community.external.organicImpressions, 212),
        earnedMediaValue: cnt(b.community.external.earnedMediaValue, 213),
        topAdvocates: Math.max(1, cnt(b.community.external.topAdvocates, 214)),
      },
    },
    graphs: {
      retention: {
        d1: pct(b.graphs.retention.d1, 220),
        d7: pct(b.graphs.retention.d7, 221),
        d30: pct(b.graphs.retention.d30, 222),
        series: b.graphs.retention.series.map((r, i) => ({
          day: r.day,
          current: r.day === "D0" ? 100 : pct(r.current, 230 + i),
          previous: r.day === "D0" ? 100 : pct(r.previous, 240 + i),
        })),
      },
      kFactor: b.graphs.kFactor.map((r, i) => ({ month: r.month, k: num(r.k, 250 + i, 2) })),
      velocity: b.graphs.velocity.map((r, i) => ({ day: r.day, players: cnt(r.players, 260 + i) })),
    },
  };
}

/* ------------------------------ REGION_ANALYTICS ------------------------------ */

// Slide-6 share of the engaged base per macro-region (map shows only top countries,
// so a macro's factor exceeds the sum of its visible countries).
const MACRO_FACTORS: Record<MacroRegion, number> = {
  NA: 0.29,
  EU: 0.24,
  APAC: 0.56,
  LATAM: 0.1,
  MEA: 0.05,
};

// The master viewership table (slide 6): keep these exact values on macro pages so the
// master table and each region's own split agree.
const MACRO_VIEWERSHIP: Record<MacroRegion, { viewers: number; gamified: number }> = {
  NA: { viewers: 18400, gamified: 11200 },
  EU: { viewers: 12100, gamified: 6900 },
  APAC: { viewers: 22900, gamified: 15800 },
  LATAM: { viewers: 6300, gamified: 3400 },
  MEA: { viewers: 3100, gamified: 1500 },
};

const buildRegionAnalytics = (): Record<string, RegionAnalytics> => {
  const out: Record<string, RegionAnalytics> = {};

  // Global = the untouched baseline.
  out["global"] = { code: "global", name: "Global", factor: 1, ...GLOBAL_BASE };

  for (const r of MACRO_REGIONS) {
    const entry = scaleAnalytics(r.code, r.label, MACRO_FACTORS[r.code]);
    // pin the viewers/gamified split to the master table's exact numbers
    entry.screenTime.viewers = MACRO_VIEWERSHIP[r.code].viewers;
    entry.screenTime.gamified = MACRO_VIEWERSHIP[r.code].gamified;
    out[r.code] = entry;
  }

  const totalUsers = COUNTRY_DATA.reduce((s, c) => s + c.users, 0);
  for (const c of COUNTRY_DATA) {
    const entry = scaleAnalytics(c.code, c.name, c.users / totalUsers, regionForCountry(c.code));
    // the map and the country strip must agree on users
    entry.strip.users = c.users;
    out[c.code] = entry;
  }

  return out;
};

export const REGION_ANALYTICS: Record<string, RegionAnalytics> = buildRegionAnalytics();

/** Lookup that tolerates lower/upper case; returns undefined for unknown codes. */
export function getRegionAnalytics(code: string): RegionAnalytics | undefined {
  return REGION_ANALYTICS[code] ?? REGION_ANALYTICS[code.toUpperCase()] ?? (code.toLowerCase() === "global" ? REGION_ANALYTICS["global"] : undefined);
}

/* ------------------------------ format helpers ------------------------------ */

export const fmtCount = (v: number): string =>
  v >= 1_000_000 ? `${(v / 1_000_000).toFixed(2)}M` : v >= 10_000 ? `${(v / 1000).toFixed(1)}K` : v.toLocaleString();

export const fmtMoney = (v: number): string =>
  v >= 1_000_000 ? `$${(v / 1_000_000).toFixed(1)}M` : v >= 1000 ? `$${(v / 1000).toFixed(0)}K` : `$${v.toFixed(2)}`;

export const fmtDuration = (secs: number): string => {
  const m = Math.floor(secs / 60);
  const s = Math.round(secs % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
};

export const TIME_RANGE_LABELS: Record<string, string> = {
  "24h": "Last 24 hours",
  "7d": "Last 7 days",
  "30d": "Last 30 days",
  "90d": "Last 90 days",
  "12m": "Last 12 months",
  all: "All time",
  custom: "Custom range",
};
