export enum RouteNames {
  // Slug routes
  METRICS = 'metrics',
  HEALTH = 'health',
  AUTH = 'auth',
  ADMIN = 'admin',
  DEVICES = 'devices',
  USERS = 'users',
  MEDIA = 'media',
  NOTIFICATIONS = 'notifications',
  AI = 'ai',
  WEBHOOKS = 'webhooks',
  API_DOCS = 'api',
  TRACING = 'tracing',

  // Named routes
  DEV_TOOLS = 'dev-tools',
  QUEUES_UI = 'admin/queues',
  HEALTH_UI = 'health-ui',
  LOGIN = 'login',
  LOGOUT = 'logout',
  REGISTER = 'register',
  REFRESH = 'refresh',
  CHANGE_PASSWORD = 'change-password',
  FORGOT_PASSWORD = 'forgot-password',
  RESET_PASSWORD = 'reset-password',
  VERIFY_EMAIL = 'verify-email',
  MFA_SETUP = 'mfa/setup',
  MFA_VERIFY = 'mfa/verify',
  TEST = 'test',
  CUSTOM = 'custom',
  STATUS = 'status',
}
