---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  volumeName: grafana-pv
  storageClassName: local-path-expandable
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
