apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  namespace: <namespace-name>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend-prod
    spec:
      imagePullSecrets:
      - name: docker-creds
      containers:
      - name: backend-prod
        image: <image-uri>
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: backend-configmap
        resources:
          requests:
            cpu: "1000m"       
            memory: "1024Mi"   
          limits:
            cpu: "2000m"       
            memory: "2048Mi"
      - name: nginx-sidecar
        image: nginx:alpine
        ports:
          - name: nginx-sidecar-metrics
            containerPort: 9010
        volumeMounts:
          - name: nginx-sidecar-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-sidecar-config
          configMap:
            name: nginx-sidecar-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-prod
  namespace: <namespace-name>
spec:
  selector:
    app: backend-prod
  ports:
    - name: backend-port
      protocol: TCP
      port: <svc-port> ##port in which your service should run. Note: this cannot de duplicate in type LoadBalancer.
      targetPort: <app-port> ##port in which your app runs
    - name: nginx-sidecar-metrics
      protocol: TCP
      port: 9010
      targetPort: 9010
  type: LoadBalancer
