---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-pvc
  namespace: monitoring
spec:
  volumeName: loki-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-expandable
  resources:
    requests:
      storage: 15Gi